In [1]:
import numpy as np

In [5]:
n1=np.array([3,4,5,6])
print(n1)

[3 4 5 6]


In [11]:
n2=np.array([[1,2,3,4],[3,4,5,6]])
print(n2)

[[1 2 3 4]
 [3 4 5 6]]


In [18]:
n3=np.zeros([3,5],dtype='int32')
print(n3)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [22]:
n4=np.ones([2,3,3],dtype='int32')
print(n4)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [24]:
n5=np.empty([1,3])
print(n5)

[[8.43178659e-312 0.00000000e+000 2.03489601e+174]]


In [26]:
n6=np.arange(10)
print(n6)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
n7=np.arange(-5,6,1)
print(n7)

[-5 -4 -3 -2 -1  0  1  2  3  4  5]


In [46]:
n8=np.linspace(0,20,num=8)
print(n8)

[ 0.          2.85714286  5.71428571  8.57142857 11.42857143 14.28571429
 17.14285714 20.        ]


In [50]:
n9=np.full([2,5],8)
print(n9)

[[8 8 8 8 8]
 [8 8 8 8 8]]


In [56]:
n5.fill(9)
print(n5)

[[9. 9. 9.]]


In [ ]:
Accessing array


In [68]:
print(n1[0],n1[-1])

3 6


In [84]:
print(n2)
print(n2[1,0])
#row and column
# 1 is row number and 0 is position
print(n2[1])
#or
print(n2[:,3])
# print full array

[[1 2 3 4]
 [3 4 5 6]]
3
[3 4 5 6]
[4 6]


In [90]:
print(n4)
n4[1,1,2]=10
print(n4)

[[[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]

 [[ 1  1  1]
  [ 1 10  1]
  [ 1  1  1]]]
[[[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]

 [[ 1  1  1]
  [ 1 10 10]
  [ 1  1  1]]]


In [ ]:
#Size and Shape

In [92]:
print(n4)
print(n4.ndim)

[[[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]

 [[ 1  1  1]
  [ 1 10 10]
  [ 1  1  1]]]
3


In [94]:
print(n4.shape)

(2, 3, 3)


In [96]:
print(n4.size)

18


In [98]:
print(n4.dtype)

int32


In [100]:
print(n4.itemsize)  # 4 bytes required for storing one element in array

4


In [102]:
print(n4.nbytes) #72 bytes for storing whole array 18 x 4 = 72

72


In [ ]:
#Sorting


In [108]:
n10=np.array([3,5,1,2,7,8,9,2])
n=np.sort(n10)
print(n)

[1 2 2 3 5 7 8 9]


In [114]:
n11=np.array([[6,2,7],[5,10,1]])
np.sort(n11)
#in 2 dimensional array each row is sorted

array([[ 2,  6,  7],
       [ 1,  5, 10]])

In [116]:
# in 2 dimensional array  to sort coloumn wuise
np.sort(n11,axis=0)
# default axis=-1

array([[ 5,  2,  1],
       [ 6, 10,  7]])

In [120]:
np.sort(n11,axis=1)


array([[ 2,  6,  7],
       [ 1,  5, 10]])

In [122]:
#Reshaping and Array Conversion

In [124]:
print(n10)

[3 5 1 2 7 8 9 2]


In [134]:
n12=n10.reshape(2,4)
print(n12)

[[3 5 1 2]
 [7 8 9 2]]


In [142]:
# joining 2 arrays
n13=np.arange(4)
n14=np.arange(5,9)
print(n13)
print(n14)
n15=np.concatenate((n13,n14))
print(n15)

[0 1 2 3]
[5 6 7 8]
[0 1 2 3 5 6 7 8]


In [148]:
#converting 1d array to 2d array
n16=np.arange(8)
print(n16)
n17=n16[np.newaxis,:]
print(n17)
print(n16.shape)
print(n17.shape)
n18=n16[:,np.newaxis]
print(n18)
print(n18.shape)

[0 1 2 3 4 5 6 7]
[[0 1 2 3 4 5 6 7]]
(8,)
(1, 8)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)


In [150]:
#column wise
n19=np.expand_dims(n16,axis=1)
print(n19)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [152]:
#row wise
n20=np.expand_dims(n16,axis=0)
print(n20)

[[0 1 2 3 4 5 6 7]]


In [ ]:
#Indexing and slicing

In [168]:
n21=np.arange(10)
print(n21)
print(n21[n21<5])
print(n21[(n21>3) & (n21<8)])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[4 5 6 7]


In [170]:
five_up=n21>5
print(five_up)
print(n21[five_up])

[False False False False False False  True  True  True  True]
[6 7 8 9]


In [174]:
#nedd index
n21[6]=100
print(n21)
print(np.nonzero(n21>5))

[  0   1   2   3   4   5 100   7   8   9]
(array([6, 7, 8, 9], dtype=int64),)


In [178]:
print(n21[3:8])

[  3   4   5 100   7]


In [ ]:
#Stack,Split

In [184]:
# Horizontal joining 
n22=np.array([[1,2],[3,4]])
n23=np.array([[5,6],[7,8]])
np.hstack((n22,n23))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [186]:
np.vstack((n22,n23))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [202]:
#split
n24=np.arange(20)
print(n24)
np.hsplit(n24,4)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

In [204]:
#COPY

In [215]:
# shallow copy
n25=n24
print(n25)
n24[0]=50
print(n24)
print(n25)
#After copy only the reference is copied but not the elements 
#so if we change the original array n 24 to n25 
# the value is alos changed in n25

[50  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[50  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[50  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [219]:
#deep copu
n26=n24.copy()
n24[1]=200
print(n26)
print(n24)
print(n26)

[50  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 50 200   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[50  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [221]:
#Maths Function

In [223]:
print(n22)
print(n23)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [225]:
print(n22+n23)

[[ 6  8]
 [10 12]]


In [227]:
print(n23-n22)

[[4 4]
 [4 4]]


In [229]:
print(n22*n23)

[[ 5 12]
 [21 32]]


In [235]:
print(n23//n22)

[[5 3]
 [2 2]]


In [247]:
print(n26)
print(n26.sum())
print(n26.max())
print(n26.min())
print(n26*10)
print(n26+10)

[50  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
240
50
1
[500  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190]
[60 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [273]:
#trignometry values
print(np.cos(n26))

[ 0.96496603  0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334
  0.66031671  0.98870462]


In [249]:
#Random Numbers

In [255]:
np.random.rand(3,3)

array([[0.84418815, 0.03460397, 0.66462538],
       [0.64324429, 0.18693262, 0.93823963],
       [0.51776301, 0.94718058, 0.92487404]])

In [269]:
np.random.randint(20,size=(4,2))
#random vaues below 20

array([[ 1, 12],
       [17,  0],
       [15,  8],
       [ 3,  6]])

In [275]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [277]:
#Searching

In [287]:

#searchig
x=np.array([1,2,3,4,5,6,7,8,9])
z=int(input("hello ->"))
y=np.where(x==z)
a=np.where(x%2==1)
print(a)
print(y)

hello -> 4


(array([0, 2, 4, 6, 8], dtype=int64),)
(array([3], dtype=int64),)


In [301]:
#searchsorted()
x=np.array([1,2,3,4,5,6,7,8,9])
b=np.searchsorted(x,4,side="right")
c=np.searchsorted(x,[2,4,6])
print(c)

print(b)
#search values and return its index

[1 3 5]
4
